# Generated by Django 5.0.3 on 2024-03-26 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social_networks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinfo',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Social_networks.category'),
        ),
    ]
