# Generated by Django 5.0.3 on 2024-03-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social_networks', '0003_alter_personinfo_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=25)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='personinfo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='Social_networks.usertag'),
        ),
    ]
