# Generated by Django 5.0.3 on 2024-03-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social_networks', '0004_usertag_personinfo_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personinfo',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='personinfo',
            name='tags',
        ),
        migrations.AddField(
            model_name='personinfo',
            name='photo',
            field=models.ImageField(blank=True, height_field=1080, upload_to='', width_field=1920),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='login',
            field=models.CharField(db_index=True, max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='UserTag',
        ),
    ]
