# Generated by Django 5.0.3 on 2024-03-28 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social_networks', '0005_remove_personinfo_cat_remove_personinfo_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinfo',
            name='acc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='Social_networks.accounts'),
        ),
    ]
