# Generated by Django 5.0.3 on 2024-04-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social_networks', '0006_personinfo_acc'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='personinfo',
            name='acc',
        ),
        migrations.AddField(
            model_name='personinfo',
            name='photos',
            field=models.ManyToManyField(to='Social_networks.personphotos'),
        ),
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
