# Generated by Django 5.0.3 on 2024-04-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social_networks', '0009_personinfo_descrip_personinfo_friends_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personinfo',
            options={'verbose_name': 'Информация о аккаунте', 'verbose_name_plural': 'Информация о аккаунтах'},
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='date_of_birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='firstname',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='lastname',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='photo',
            field=models.ImageField(blank=True, height_field=1080, upload_to='person_photo', width_field=1920),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='photos',
            field=models.ManyToManyField(related_name='user', to='Social_networks.personphotos', verbose_name='Фотография профиля'),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Слаг'),
        ),
    ]
