# Generated by Django 5.0.3 on 2024-04-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social_networks', '0010_alter_personinfo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinfo',
            name='profile_hat',
            field=models.ImageField(blank=True, upload_to='person_photo/hats'),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='person_photo'),
        ),
    ]
