# Generated by Django 5.0.3 on 2024-03-26 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social_networks', '0002_personinfo_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinfo',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Social_networks.category'),
        ),
    ]
