# Generated by Django 5.0.3 on 2024-04-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social_networks', '0007_personphotos_remove_personinfo_acc_personinfo_photos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinfo',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='photos',
            field=models.ManyToManyField(related_name='user', to='Social_networks.personphotos'),
        ),
    ]
