# Generated by Django 5.0.3 on 2024-04-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social_networks', '0008_personinfo_occupation_alter_personinfo_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinfo',
            name='descrip',
            field=models.TextField(blank=0, default='Привет! Я использую Ailes!'),
        ),
        migrations.AddField(
            model_name='personinfo',
            name='friends',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personinfo',
            name='subscribers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personinfo',
            name='subscribes',
            field=models.IntegerField(default=0),
        ),
    ]
